---

- hosts: all
  become: true
  tasks:

  - name: apt update
    apt:
      update_cache: yes


  - name: install nginx
    apt:
      name: nginx
      state: latest


  - name: install php for nginx
    apt:
      name: php-fpm    
      state: latest
