---

- hosts: all
  become: true
  tasks:

  - name: install nginx, php-fpm via apt
    apt:
      name: 
        - nginx
        - nginx-core
        - nginx-common  
        - php-fpm
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

