---

- hosts: all
  become: true
  tasks:

  - name: apt update
    apt:
      update_cache: yes


  - name: remove nginx
    apt:
      name: nginx
      state: absent


  - name: remove php for nginx
    apt:
      name: php-fpm    
      state: absent 
