---

- hosts: all
  become: true
  tasks:

  - name: install nginx, nginx-core, nginx-common, php-fpm
    package:
      name: 
        - nginx
        - nginx-core
        - nginx-common  
        - php-fpm
      state: absent
      purge: yes

