---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    apt:
      update_cache: yes
      upgrade: dist
        

- hosts: webservers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

- hosts: db_servers
  become: true
  tasks:

  - name: install mariaDB
    apt:
      name: 
        - mariadb-server
      state: latest


- hosts: fileservers
  become: true
  tasks: 

  - name: install samba
    apt: 
      name: samba
      state: latest 
